# Generated by Django 5.0.3 on 2024-03-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('designer', 'Designer')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
